### ISSUE TITLE
Segfault when shooting a zombie

### ISSUE THREAD

**Issue by raku-cat** [ForrestMarkX/glua-ZombieMaster#5]
I admittedly haven't been able to test this very thoroughly, but I'll try to be descriptive as possible.

I'm running the latest gmod server version, I have the latest git version of zombiemaster on the server, the server is running on debian buster.

When a user specifically shoots a zombie(fists don't cause this), after the first 2 or 3 shots the server segfaults.
Here is a debug.log with sensitive info removed
```
----------------------------------------------
CRASH: Tue Sep 19 18:17:45 CDT 2017
Start Line: ./srcds_linux -game garrysmod -debug -console -ip 192.168.1.36 -authkey redacted +sv_setsteamaccount redacted +maxplayers 20 +host_workshop_collection 1134678035 +gamemode zombiemaster +map zm_gasdump_b4
[New LWP 29897]
[New LWP 29904]
[New LWP 29898]
[New LWP 29899]
[New LWP 29912]
[New LWP 29900]
[New LWP 29915]
[New LWP 29919]
[New LWP 29928]
[New LWP 29929]
[New LWP 29913]
[New LWP 29934]
[New LWP 29901]
[New LWP 29902]
[New LWP 29903]
Core was generated by `./srcds_linux -game garrysmod -debug -console -ip 192.168.1.36 -authkey redacted'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf244cb38 in ?? ()
[Current thread is 1 (LWP 29897)]
#0  0xf244cb38 in ?? ()
Backtrace stopped: Cannot access memory at address 0xffc336c0
No symbol table info available.
eax            0xffc33730       -3983568
ecx            0xf735650c       -147495668
edx            0x10     16
ebx            0x0      0
esp            0xffc336c0       0xffc336c0
ebp            0xffc336e8       0xffc336e8
esi            0x0      0
edi            0x0      0
eip            0xf244cb38       0xf244cb38
eflags         0x10286  [ PF SF IF RF ]
cs             0x23     35
ss             0x2b     43
ds             0x2b     43
es             0x2b     43
fs             0x0      0
gs             0x63     99
No shared libraries loaded at this time.
End of Source crash report
----------------------------------------------
```
And here is a log of the console output
```
Segmentation fault (core dumped)
BFD: Warning: /home/josh/gmod/core is truncated: expected core file size >= 463876096, found: 1163264.
Cannot access memory at address 0xf77ba908
Cannot access memory at address 0xf77ba904
Failed to read a valid object file image from memory.
Cannot access memory at address 0xf77ba908
Cannot access memory at address 0xf77ba904
debug.cmds:5: Error in sourced command file:
No function contains program counter for selected frame.
email debug.log to linux@valvesoftware.com
Mon Sep 18 21:03:21 CDT 2017: Server restart in 10 seconds
```

Let me know if you need any other info.

**Comment by ForrestMarkX** [comment]
Does this happen with Shamblers, Banshees and Hulks only? Or does it also happen when killing Immolators and Drifters?

**Comment by ForrestMarkX** [comment]
Try using the latest commit in the Github and see if the crash still happens

**Comment by raku-cat** [comment]
Just to clarify how I should be using the git version, on the server I clone the repo and put it in the `gamemodes` folder in a folder named `zombiemaster`, and then let the clients do their own thing?

**Comment by ForrestMarkX** [comment]
Yes but make sure you don't have the workshop version installed

**Comment by raku-cat** [comment]
Workshop one on the client or the server?

**Comment by ForrestMarkX** [comment]
Server

**Comment by raku-cat** [comment]
Looks like that fixed it :D 
Just got back from playing a few full rounds with randoms, there's a bit of lag at times with the zombies but I can't definitively tell if it's not just a map or hardware problem. Regardless, this problem seems to be fixed so I'll close this issue. Thanks :)
